spring:
    profiles:
        active: dev # Altere para "dev" ao utilizar outro PC para acessar o banco H2, e para "test" ao usar o Docker Compose.
    application:
      name: vagasFatec

    datasource:
      url: ${SPRING_DATASOURCE_URL}
      username: ${SPRING_DATASOURCE_USERNAME}
      password: ${SPRING_DATASOURCE_PASSWORD}

    jpa:
      hibernate:
        ddl-auto: ${SPRING_JPA_HIBERNATE_DDL_AUTO:update}
      show-sql: true
app:
  upload:
    curriculos-dir: "C:/Users/ryan.moscardini/Desktop/SiteVagasFatec/uploads/curriculos"
jwt:
  token: u5P+z8xK9vR3fW1L6mN2jB8Yq4tS0V7hX9aZ1cE5gD8=
