name: Build e Push Docker

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Login no Docker Hub
        run: echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      - name: Build da imagem
        run: docker build -t ryanmosc/backend-vagas-fatec:${{ github.run_number }} .

      - name: Tag latest
        run: docker tag ryanmosc/backend-vagas-fatec:${{ github.run_number }} ryanmosc/backend-vagas-fatec:latest

      - name: Push da imagem
        run: |
          docker push ryanmosc/backend-vagas-fatec:${{ github.run_number }}
          docker push ryanmosc/backend-vagas-fatec:latest